version: '3.9'

services:
  database:
    image: postgres
    container_name: postgres_rentx
    ports:
      - 3301:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=@Ro0/3pWdhjY
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
    
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: rentx
  #   ports:
  #    - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local